version: "3"
services:
  prestashop:
    image: prestashop/prestashop
    networks:
      myprestashop:
    ports:
      - 8181:80
    links:
      - mariadb:mariadb
    depends_on:
      - mariadb
    volumes:
      - /srv/Configs/PrestaShop/src:/var/www/html
      - /srv/Configs/PrestaShop/src/modules:/var/www/html/modules
      - /srv/Configs/PrestaShop/src/themes:/var/www/html/themes
      - /srv/Configs/PrestaShop/src/override:/var/www/html/override
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=mariadb
      - DB_USER=root
      - DB_PASSWD=mycustompassword
      - DB_NAME=prestashop
      - PS_INSTALL_AUTO=0

  mariadb:
    image: mariadb
    networks:
      myprestashop:
    volumes:
      - /srv/Databases/PrestaShop:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mycustompassword
      - MYSQL_DATABASE=prestashop

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      myprestashop:
    links:
      - mariadb:mariadb
    ports:
      - 1235:80
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=mycustompassword

networks:
  myprestashop:
    external: true
